### ISSUE TITLE
TestRequest is not exported

### ISSUE THREAD

**Issue by xescuder** [microcks/microcks-testcontainers-node#1]
### Describe the bug

import { MicrocksContainer, TestRequest } from "@microcks/microcks-testcontainers";

Is giving the error that TestRequest is not found.

### Actual behavior

index.js is doing:
export { MicrocksContainer, StartedMicrocksContainer } from "./microcks-container";

but not exporting interfaces or enums.

**Comment by lbroudoux** [comment]
New version `0.1.1` has been pushed to NPM. Let me know if that's ok on your side.

**Comment by xescuder** [comment]
Yes, now works, thanks!

**Comment by xescuder** [comment]
Sorry, but I prefer to use javascript, instead typescript, and it seems can't be used:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/escuderx/Projects/allure-microcks/node_modules/@microcks/microcks-testcontainers/src/index.ts
