### ISSUE TITLE
Support microcks-testcontainers-dotnet?

### ISSUE THREAD

**Issue by thangchung** [microcks/microcks-testcontainers-node#19]
### Reason/Context

We come from the .NET community and would like to have the ability to use microrocks with testcontainers

### Description

We just came around in some communities like Java, Go, and Node and saw there are native supports to run microrocks with testcontainers, and see that there are a lot of benefits on integration tests, and mocking some external services (via OpenAPI or even AsyncApi specs). My question is do we have a plan to support it for .NET/C#? Thank you very much.

**Comment by thangchung** [comment]
Sorry. I posted in the wrong place. Ignored it.

**Comment by lbroudoux** [comment]
This is now available in microcks/microcks-testcontainers-dotnet ! 🚀
