### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by xescuder** [microcks/microcks-testcontainers-node#3]
### Describe the bug

   /Users/escuderx/Projects/allure-microcks/node_modules/@microcks/microcks-testcontainers/src/index.ts:16
    export { MicrocksContainer, StartedMicrocksContainer,
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      2 |
      3 | const { Network } = require('testcontainers');
    > 4 | const { MicrocksContainer, TestRunnerType } = require('@microcks/microcks-testcontainers');
        |                                               ^
      5 |
      6 | describe("MicrocksContainer", () => {
      7 |   jest.setTimeout(180_000);

**Comment by lbroudoux** [comment]
Hey Xavier, 

Sorry, I think I screwed up things regarding the packaging... I'm not a JS champion. Here's a new archive with a new way to package things up. Could you please check it out and tell me if it's now ok?

[microcks-microcks-testcontainers-0.1.1.tgz](https://github.com/microcks/microcks-testcontainers-node/files/12820298/microcks-microcks-testcontainers-0.1.1.tgz)

**Comment by xescuder** [comment]
Yes, now I can import correctly! Thanks.

**Comment by lbroudoux** [comment]
Thanks for feedback! Releasing the `0.1.2` in a few minutes!
